export default [{ position: 0, name: "User Profile" },
{ position: 1, name: "User Group" },
{ position: 2, name: "Chat" },
{ position: 3, name: "LiveChat Crisp" },
{ position: 4, name: "Info" },
{ position: 5, name: "Jackpot Money Bag" },
{ position: 6, name: "All Bets" },
{ position: 7, name: "Biggest Wins" },
{ position: 8, name: "Leader Board" },
{ position: 9, name: "Latest Wins" },
{ position: 10, name: "Latest Bets" },
{ position: 11, name: "Email" },
{ position: 12, name: "Rules" },
{ position: 13, name: "Sound" },
{ position: 14, name: "Maximize" },
{ position: 15, name: "Security" },
{ position: 16, name: "My Bets" },
{ position: 17, name: "Wallet" },
{ position: 18, name: "Deposits" },
{ position: 19, name: "Withdraws" },
{ position: 20, name: "Affiliates" },
{ position: 20, name: "Affiliates" },
{ position: 20, name: "Affiliates" },
{ position: 21, name: "Preferences" },
{ position: 22, name: "Affiliate Referral" },
{ position: 23, name: "Arrow" },
{ position: 24, name: "Arrow Up" },
{ position: 25, name: "Arrow Down" },
{ position: 26, name: "Jackpot BigWin" },
{ position: 27, name: "Copy" },
{ position: 28, name: "Country Restricted" },
{ position: 29, name: "Logout" }]