/* eslint-disable react/no-array-index-key */
import React, { PureComponent } from 'react';


class TermsConditions extends PureComponent {
    
    constructor(props){
        super(props);
    }

    render() {        
        return (
            <div>
                
                <div style={{textAlign: "center"}}>
                    <h2 style={{marginBottom: 20, marginTop: 10}}>Terms & Conditions</h2>
                </div>
                
                Please read these terms and conditions that follow ("Terms") carefully as they form a contract between you and BetBlock Technology LDA, doing business under the registered trademark BetProtocol, herein: “BetProtocol”, “we”, “our” or “us”. These Terms govern your access and use of our Services. “Services” refers individually and collectively to the BetProtocol website, BetProtocol platform, APIs, games, gaming systems, blockchain based systems, smart contracts, mobile & web applications (each, an ““App” or “Dapp”), and any software services provided by BetProtocol, as well as all written or electronic materials including software, data, text, audio, video, images, photos, graphics, or other content (“Content”). These Terms refer to the individual or entity using the Service (including any component of the Service) as “you” or “your”.
                By accepting these Terms electronically (for example, clicking “I Agree”), accessing or using the Services, purchasing Services, registering for an account with us, executing these Terms, or accepting an Order that references these Terms, you are accepting and agreeing to these Terms and the policies and guidelines referenced in these Terms. If you do not agree to these Terms then you may not use the Services.
                We will notify you of amendments to these Terms by either: (a) posting the revised terms on our website; (b) sending you an email notification to the email address that you provided to us as part of your account registration, or a notification via SMS or other messaging service; or (c) presenting the revised Terms to you when you log into the Services. It is your responsibility to provide and update your external email address, check for such notices, and make sure our notices have not been trapped by your spam filter. It is your responsibility to periodically revisit these Terms as posted on our website. The such updated Terms will become effective the earlier of: (a) when you accept it online or offline, (b) twenty (20) days after we post or email the update, in which case your continued use of any of the Services or failure to cancel your account will indicate your acceptance of the amendment.
                THESE TERMS REQUIRE THE USE OF ARBITRATION TO RESOLVE DISPUTES ON AN INDIVIDUAL BASIS, RATHER THAN JURY TRIALS OR ON RESOLUTION BY CLASS ACTION, AS FURTHER DESCRIBED IN SECTION 8.

                <h3 style={{marginTop: 30}}>1. Digital Assets and the Service</h3>

                <h4 style={{marginTop: 20, marginBottom: 10}}>1.1 About Digital Assets.</h4>
                The Service does not send or receive money. The Service enables you to interface with various cryptocurrency networks to view and transmit information about a public cryptographic key commonly referred to as a cryptocurrency address – sometimes referred to herein as a “cryptocurrency account”. To transmit information about a cryptocurrency account (for example, an Ethereum account) to the cryptocurrency network (for example, the Ethereum Network), the private key(s) corresponding with the cryptocurrency account is required. The Service requires three private cryptographic keys to be associated with each cryptocurrency account and BetProtocol controls only one of these private keys. Two of the three private keys associated with a cryptocurrency wallet are needed to effect a “transfer” of cryptocurrency from a cryptocurrency account (i.e., disassociate cryptocurrency from one cryptocurrency wallet and re-associate cryptocurrency with another cryptocurrency wallet). Once the cryptocurrency network recognizes the information you send from the Service and validates it, the information is broadcasted to other individuals and companies in the cryptocurrency network and the Service cannot be used by you to cancel or reverse cryptocurrency-to-cryptocurrency transactions. The same is true for any other cryptocurrency and digital assets for which we provide wallets (“Digital Asset”) including (as of the last update of these Terms) cryptocurrency, Ether, XRP, and Litecoin, [depending on what wallet services the customer has ordered from BetProtocol.]
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>1.2 Digital Asset Protocols and Network Fees.</h4>
                BetProtocol does not own or control the underlying software protocols which govern the operation of Digital Currencies. Digital Asset protocols are subject to changes in protocol rules (referred to as “forks”), and such forks may materially affect the value, function, or name of the Digital Asset. You acknowledge and agree (i) that BetProtocol is not responsible for operation of the underlying Digital Asset protocols and that BetProtocol makes no guarantee of their functionality, security, or availability; and (ii) if a fork occurs, BetProtocol may temporarily suspend the Services relating to the Digital Asset affected, and BetProtocol may decide not to support the forked protocol entirely or may configure its Services to enable you to transfer the affected Digital Asset.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>1.3 Managing Your Keys.</h4>
                BetProtocol controls only one of the three private keys for a Digital Asset wallet provided by the Service. You are solely responsible for maintaining the security of the other two private keys. If you appoint a third party to control one or more of your private key(s), whether or not such appointment is made through the Service (e.g., through a key recovery service), BetProtocol is not responsible for the actions or omissions of such third party. Control of these keys will allow such third party to transfer all of your Digital Assets from your wallets and you may never regain those Digital Assets.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>1.4 Wallets and Digital Assets.</h4>
                Your wallets and your Digital Assets are your responsibility. BetProtocol cannot cause transactions transferring Digital Assets from your wallets except in conjunction with a request or instruction through the Service by you or someone holding your private keys. You may need both of the private keys not controlled by BetProtocol to initiate transfer of Digital Assets.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>1.5 Passwords and Security.</h4>
                You are responsible for maintaining adequate security and control of any and all log in IDs, passwords, private keys, personal identification numbers (PINs), and any other codes that you use to access the Service. You will be solely responsible for the private keys that we provide to you or that you generate for our wallets, and maintaining secure back-ups. You will prevent unauthorized access to or use of the Services using your account credentials or private keys, and notify us promptly of any such unauthorized access or use. You must keep your account ID, passwords and any other account credentials confidential and not authorize any third party to access or use the Service on your behalf, unless we provide an approved mechanism for such use. You will notify us at support@BetProtocol.com of any security breach of your account, system or network as soon as possible. You will cooperate with us in the investigation of any suspected unauthorized access to or use of the Services using your account credentials or private keys, and any security breach of your account, system, or network, and provide us with the results of any third-party forensic investigation that you undertake. You will be responsible, and BetProtocol will have no liability, for all activity that takes place with your BetProtocol Service account accessed using your account credentials, whether or not authorized by you.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>1.6 Identity Authentication.</h4>
                You must be at least 18 years old, or such higher age required by applicable law, to register for a BetProtocol Service account. You will provide BetProtocol and its affiliates with accurate, current, and complete information about yourself as prompted by the registration process or as BetProtocol may, from time to time request, and keep such information updated. You authorize BetProtocol to make such inquiries that it considers necessary to validate your identity and you agree that BetProtocol may do so using third party service providers.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>1.7 Non-BetProtocol Applications.</h4>
                The Services may contain features designed to interoperate with a third party service, program, website or Content that is provided, owned or licensed by you or a third party (“Non-BetProtocol Application”). To use such features, you must procure Non-BetProtocol Applications from the providers of such Non-BetProtocol Applications, and may be required to grant us access to your account on the Non-BetProtocol Applications. If you enable a Non-BetProtocol Application for use with the Services, you grant us permission to allow the provider of that Non-BetProtocol Application to access your information and End User Data as required for the interoperation of that Non-BetProtocol Application with the Services. We are not responsible for any disclosure, modification or deletion of Content or End User Data resulting from access by a Non-BetProtocol Application. If the provider of a Non-BetProtocol Application ceases to make the Non-BetProtocol Application available for interoperation with the corresponding Services features on reasonable terms, we may cease providing those Services features without entitling you to any refund, credit, or other compensation.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>1.8 Third Party Services.</h4>
                In connection with your use of the Services, you may be made aware of or offered services, Content, features, products, Non-BetProtocol Applications, offers and promotions provided by third parties (individually and collectively, “Third Party Services”). We may make Third Party Services available to you. However, our inclusion or promotion of Third Party Services does not reflect a sponsorship, endorsement, approval, investigation, verification, certification or monitoring of such Third Party Services by BetProtocol. Your acquisition of Third Party Services, and any exchange of data between you and any non-BetProtocol provider, is solely between you and such provider. BetProtocol does not warrant Third Party Services in any way. Under no circumstances will we have any liability for Third Party Services. Use Third Party Services at your own risk, and under terms and conditions between you and the provider of Third Party Services that are different than the provisions of these Terms.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>1.9 Taxes.</h4>
                Our fees do not include any taxes, levies, duties or similar governmental assessments of any nature, including, for example, value-added, sales, use or withholding taxes, assessable by any jurisdiction whatsoever (collectively, “Taxes”). You are responsible for paying all Taxes associated with your purchases hereunder. If we have the legal obligation to pay or collect Taxes for which you are responsible, we will invoice you and you will pay that amount unless you provide us with a valid tax exemption certificate authorized by the appropriate taxing authority. For clarity, we are solely responsible for Taxes assessable against us based on our income, property and employees (“BetProtocol Taxes”). If applicable law requires you to withhold BetProtocol Taxes from your payment(s) to BetProtocol, you will provide reasonable assistance to BetProtocol in connection with such BetProtocol Taxes by: (a) promptly providing BetProtocol with valid tax receipts and other required documentation evidencing your payment of such BetProtocol Taxes; and (ii) assisting BetProtocol in filing applications to reduce such BetProtocol Taxes.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>1.10 Risks.</h4>
                You acknowledge that using Digital Assets, their networks and protocols, involves serious risks. It is your duty to learn about all the risks involved with Digital Assets, their protocols and networks. There are many, and describing these risks could fill chapters of a book. For example, the value of Digital Assets can change rapidly, increase or decrease unexpectedly, and potentially even fall to zero. For example, a cryptocurrency transaction may be unconfirmed for a period of time (usually less than one hour, but up to one day or longer) and may be never complete if it remains in a pending state. Further, if you send ERC 20 tokens to your ether wallet that does not support ERC 20 tokens, your tokens will be lost entirely and will not be recoverable. Even if BetProtocol alerts you to some of the risks involved with Digital Assets, their protocols and networks, BetProtocol has no responsibility to alert you to all these risks. BetProtocol has no control over, and makes no representations regarding the value of Digital Assets, or the security of their networks or protocols.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>1.11 BetProtocol Instant Transactions.</h4>
                “BetProtocol Instant” means the service provided by BetProtocol whereby BetProtocol verifies that a transfer of cryptocurrency from a wallet is not a “double-spend” before the transaction is confirmed by the cryptocurrency network. BetProtocol provides BetProtocol Instant as a Service to certain of its customers that order it. If you wish to receive cryptocurrency with the benefit of BetProtocol Instant, you will need to enter into BetProtocol’s separate written agreement for that benefit. Otherwise, you may not rely on a cryptocurrency transmission as verified by BetProtocol Instant, and BetProtocol does not make any guarantee, warranty, or other promise to you about double-spending.
                
                <h3 style={{marginTop: 20}}>2. Use of The Service</h3>
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>2.1. Your Privacy.</h4>
                Your Privacy. Please review our privacy policy located at https://www.BetProtocol.com/privacy ("Privacy Policy") to understand our commitments in maintaining your privacy. You agree to the collection, use and disclosure of information as described in Privacy Policy.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>2.2 Account Communications.</h4>
                We may send you emails regarding the Service including notices, updates, and amended Terms. We may also send you emails with promotional information and materials regarding BetProtocol's products and services that you may unsubscribe from by following instructions provided in the email.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>2.3 Suspension and Termination.</h4>
                We reserve the right, to temporarily suspend or terminate your access to the Service at any time in our sole discretion, with or without cause, and with or without notice, without incurring liability of any kind. For example, we may suspend or terminate your access to or use of the Service for: (a) the actual or suspected violation of these Terms; (b) the use of the Service in a manner that may cause BetProtocol to have legal liability or disrupt others' use of the Service, and; (c) scheduled downtime and recurring downtime, or unplanned technical problems and outages.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>2.4 Unacceptable Use.</h4>
                You will not, nor encourage or assist any third party to, (a) use any unauthorized means to gain access to the Service or use any automated process or service (such as a bot, a spider, or periodic caching of information stored by BetProtocol) to access or use the Service, or distribute instructions, software or tools for that purpose; (b) modify, alter, tamper with, repair or otherwise create derivative works of the Service; (c) interfere with or disrupt servers or networks used by BetProtocol to provide the Service; (d) damage, disable, overburden, or impair the Service (or any network connected to the Service); (e) use the account of another user at any time except by a mechanism provided by BetProtocol and authorized by such user; (f) use the Service to use the Service in any manner or for any purpose other than as expressly permitted by these Terms, the Privacy Policy, any BetProtocol user guides and policies available via the Service (“Policies”); (g) engage in any unlawful or fraudulent activity or perpetrate a hoax or engage in phishing schemes or forgery or other similar falsification or manipulation of data; (h) send unsolicited or unauthorized junk mail, spam, chain letters, pyramid schemes or any other form of duplicative or unsolicited messages, whether commercial or otherwise; or (i) advertise or promote a commercial product unless your account is subject to a separate contract governing that relationship and your compensation to BetProtocol. BetProtocol may determine, in its sole discretion, whether and what action to take in response to a claimed violation of these Terms, and any action or inaction in a particular instance will not dictate or limit our response to a future complaint.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>2.5 Product Updates.</h4>
                BetProtocol may, in its sole discretion, make unscheduled deployments of changes, updates or enhancements to the Service at any time. We may add or remove functionalities or features, and we may discontinue the Service altogether. Depending on your device settings, we may automatically check your version of the App, and automatically download to your device new versions of the App.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>2.6 License and Restrictions.</h4>
                BetProtocol grants you a personal, non-transferable, non-exclusive license to use the Service as provided to you by BetProtocol. This license is conditioned upon and restricted by the terms and conditions in these Terms. Further, this license is for personal and non-commercial use. You may not (and you may not permit anyone else to) copy, modify, create a derivative work of, reverse engineer, decompile or otherwise attempt to extract the source code of the Service, or any part thereof, except (and solely) to the extent permitted by applicable law. You may not assign (or grant a sub-license of) your rights to use the Service, grant an interest in or over your rights to use the Service, or otherwise transfer any part of your rights under these Terms. If BetProtocol provided you access to any of the Service (for example, a mobile app) in return for a fee, this license is conditioned on your payment of the fees due. These Terms do not grant to you any license or permission to copy, distribute, modify or otherwise use any application programming interface, notwithstanding any provision to the contrary. No title to or ownership of any proprietary rights related to the Service is transferred to you pursuant to these Terms. All rights not explicitly granted to you under these Terms are reserved by BetProtocol.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>2.7 BetProtocol Trademarks and Feedback.</h4>
                BetProtocol grants you no license or consent to use or display or use in any manner BetProtocol’s trademarks, service marks, logos or slogans. In the event that you provide comments, suggestions and recommendations to us with respect to the Services (including modifications, enhancements, improvements or suggested changes to the Services, or any feature or function of the Services) (collectively, "Feedback"), you hereby grant us and our affiliates a universe-wide, royalty free, irrevocable, perpetual license (with the right to grant and authorize sublicenses) to make, have made, use, import, offer for sale, sell, reproduce, distribute, modify, adapt, prepare derivative works of, display, publicly perform and otherwise exploit such Feedback without restriction, including in connection with the Services and any updates, extensions or successive versions of the Services.
                
                <h3 style={{marginTop: 20}}>3. User Content</h3>
                
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>3.1 Your Content</h4>
                You are responsible for the Content that you provide or make available via the Service (“User Content”), or that other users provide or make available. BetProtocol will have no liability of any kind as a result of the deletion of, correction of, destruction of, damage to, loss of or failure to store or encrypt any User Content. If your access to the Service is suspended or terminated, you will not have access to the User Content.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>3.2 Sharing of Content</h4>
                If you enable the features that allow you to share User Content with others, anyone you've shared User Content with (including the general public, in certain circumstances) may have access to your User Content.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>3.3 License</h4>
                You hereby grant BetProtocol and its contractors the right, to use, modify, adapt, reproduce, distribute, transmit, display and disclose User Content as reasonably necessary to provide the Service or as otherwise permitted by these Terms. You represent and warrant that: (a) you have all the rights in the User Content that you provide necessary for you to use the Service and to grant the rights in these Terms; and (b) the storage, use, display, reproduction, distribution, modification, adaptation or transmission of such User Content doesn't violate any law or these Terms.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>3.4 Responsibility</h4>
                You will: (a) be solely responsible for the nature, quality and accuracy of the User Content; (b) ensure that the User Content (including the storage or transmission thereof) complies with these Terms and any and all applicable laws, and regulations; (c) promptly handle and resolve any notices and claims relating to the User Content, including any notices sent to you by any person claiming that any User Content violates any person's rights, such as take-down notices pursuant to the Digital Millennium Copyright Act and any other notices; and (d) maintain appropriate security, protection and backup copies of the User Content, which may include, your use of additional encryption technology to protect the User Content from unauthorized access.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>3.5 Inappropriate Content</h4>
                You will not store or transmit inappropriate User Content, including any User Content: (a) containing unlawful, defamatory, threatening, pornographic, abusive, libelous or otherwise objectionable material of any kind or nature, (b) containing any material that encourages conduct that could constitute a criminal offense, or (c) that violates the intellectual property rights or rights to the publicity or privacy of others; (d) containing or that uses software viruses or other harmful or deleterious computer code, files or programs such as Trojan horses, worms, time bombs, cancelbots, or spyware; or (f) that harms, threatens, or harasses another person, organization, or BetProtocol.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>3.6 Global Storage</h4>
                You understand and consent to the storage and processing of User Content and any other personal information in Portugal. BetProtocol reserves the right to store and process personal information outside of Portugal.
                
                <h3 style={{marginTop: 20, marginBottom: 10}}>4. Export Restrictions</h3>
                
                The App is subject to applicable Portuguese export laws and regulations. You must comply with all domestic and international export laws and regulations that apply to the App. You may not transfer the App to anyone or anywhere on U.S. government or European Union exclusion lists (for example, the Commerce Department's compliance list (ww.bis.doc.gov/complianceandenforcement/liststocheck.htm). You represent and warrant that you're not on any of such lists or under the control of or an agent for anyone on such lists. You may not take a copy of the App to a U.S. or EU embargoed country (as of the date of these Terms: the Crimea region of Ukraine, Cuba, Iran, North Korea, Sudan, Syria or Venezuela) or use the Service in violation of any applicable export laws or regulations.
                
                <h3 style={{marginTop: 20, marginBottom: 10}}>5. No Warranties</h3>
                
                ACCESS TO AND USE OF THE SERVICE IS AT YOUR SOLE RISK. BetProtocol PROVIDES THE SERVICE “AS IS”, “WITH ALL FAULTS” AND “AS AVAILABLE”. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, BetProtocol MAKES NO (AND SPECIFICALLY DISCLAIMS ALL) REPRESENTATIONS OR WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, WITHOUT LIMITATION: (A) ANY WARRANTY THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE OR FREE OF HARMFUL COMPONENTS, THAT THE CONTENT WILL BE SECURE OR NOT OTHERWISE LOST OR DAMAGED; (B) ANY IMPLIED WARRANTY OF MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT; OR (C) ANY WARRANTY ARISING OUT OF ANY COURSE OF PERFORMANCE, COURSE OF DEALING OR USAGE OF TRADE. BetProtocol MAKES NO WARRANTY OR REPRESENTATION AND DISCLAIMS ALL RESPONSIBILITY AND LIABILITY FOR: (I) THE COMPLETENESS, ACCURACY, AVAILABILITY, TIMELINESS, SECURITY OR RELIABILITY OF THE SERVICES OR ANY CONTENT; (II) ANY HARM TO YOUR COMPUTER SYSTEM, LOSS OF DATA, OR OTHER HARM THAT RESULTS FROM YOUR ACCESS TO OR USE OF THE SERVICE OR ANY CONTENT; (III) THE DELETION OF, OR THE FAILURE TO STORE OR TO TRANSMIT, ANY CONTENT AND OTHER COMMUNICATIONS MAINTAINED BY THE SERVICE; AND (IV) WHETHER THE SERVICES WILL MEET YOUR REQUIREMENTS OR BE AVAILABLE ON AN UNINTERRUPTED, SECURE, OR ERROR-FREE BASIS. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM BetProtocol, ITS AFFILIATES, RELATED COMPANIES, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, REPRESENTATIVES, PARTNERS, OR LICENSORS (COLLECTIVELY, “RELEASED ENTITIES”), OR THROUGH THE SERVICES, WILL CREATE ANY WARRANTY OR REPRESENTATION.
                
                <h3 style={{marginTop: 20, marginBottom: 10}}>6. Indemnification</h3>
                
                You agree to indemnify and hold BetProtocol and its subsidiaries, affiliates, officers, agents, employees, partners, suppliers, and licensors harmless from any claim, action, investigation or demand, including reasonable attorneys' fees, arising out of or relating to: (a) User Content; (b) use of the Service by you or under your account; or (c) your violation of these Terms or of any third party rights. BetProtocol will use commercially reasonable efforts to notify you of any such claim, action, investigation or demand that is subject to your indemnification obligation.
                
                <h3 style={{marginTop: 20}}>7. Limitations of Liability</h3>
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>7.1</h4>
                IN NO EVENT WILL BetProtocol, ITS SUBSIDIARIES, AFFILIATES, OFFICERS, AGENTS, EMPLOYEES, REPRESENTATIVES, PARTNERS, SUPPLIERS, OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOST PROFITS, REVENUE, GOODWILL, LOSS OF DIGITAL ASSETS, OR USER CONTENT) HOWEVER CAUSED, UNDER ANY THEORY OF LIABILITY, INCLUDING, WITHOUT LIMITATION, CONTRACT, TORT, WARRANTY, NEGLIGENCE OR OTHERWISE, EVEN IF ANY OF THE FOREGOING PARTIES HAVE BEEN ADVISED AS TO THE POSSIBILITY OF SUCH DAMAGES.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>7.2</h4>
                IN NO EVENT WILL THE AGGREGATE LIABILITY OF BetProtocol, ITS SUBSIDIARIES, AFFILIATES, OFFICERS, AGENTS, EMPLOYEES, REPRESENTATIVES, PARTNERS, SUPPLIERS, AND LICENSORS LIABILITY ARISING FROM OR RELATING TO THESE TERMS OR THE SERVICE EXCEED THE GREATER OF: (A) $50, OR (B) THE AMOUNT PAID, IF ANY, BY YOU TO BetProtocol FOR THE SERVICE IN THE TWELVE MONTHS BEFORE YOUR CLAIM AROSE. THE FOREGOING LIMITATION APPLIES UNDER ANY THEORY OF LIABILITY, INCLUDING, WITHOUT LIMITATION, CONTRACT, TORT, WARRANTY, NEGLIGENCE OR OTHERWISE.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>7.3</h4>
                THESE LIMITATIONS AND EXCLUSIONS ALSO APPLY IF THIS REMEDY DOES NOT FULLY COMPENSATE YOU FOR ANY LOSSES OR FAILS OF ITS ESSENTIAL PURPOSE.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>7.4</h4>
                Some jurisdictions do not allow the exclusion or limitation of incidental or consequential damages. To the extent that you reside in a jurisdiction where applicable law does not permit BetProtocol to limit its liability to the extent set forth in Section 7.1, 7.2 or 7.3, then such limitations may not apply to you.
                
                <h3 style={{marginTop: 20}}>8. Arbitration</h3>
                
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>8.1</h4>
                YOU AND BetProtocol AGREE THAT ANY DISPUTE, CLAIM OR CONTROVERSY ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR ANY OF THE SERVICES (INCLUDING THE BREACH, TERMINATION, ENFORCEMENT, INTERPRETATION OR VALIDITY THEREOF, INCLUDING THE DETERMINATION OF THE SCOPE OR APPLICABILITY OF THESE TERMS TO ARBITRATE) SHALL BE DETERMINED BY BINDING ARBITRATION INSTEAD OF IN COURTS OF GENERAL JURISDICTION. The language to be used in the arbitral proceedings will be English. You agree that you and BetProtocol are each waiving the right to a trial by jury and to participate in a class action. This arbitration provision shall survive any termination of other terms.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>8.2</h4>
                The arbitrator shall not have the power to award damages that are limited or waived by these Terms (such as punitive damages, treble damages, or any other damages which are not compensatory), to the extent such limitation or waiver is permitted under applicable law, and the parties waive any right to recover any such damages. Further, the arbitrator shall have no power to issue any award that is contrary to or inconsistent with any applicable statute, case law or constitutional law, to modify, change or excuse performance of any material term of these Terms, or to award equitable relief. The arbitration proceedings and decision of the arbitrator shall be kept confidential (and may not be disclosed) by the parties or the arbitrator, except to the extent necessary to compel any award made by the arbitrator.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>8.3</h4>
                The arbitration shall be administered by Portuguese Judicial Court of Lisbon pursuant to its Rules and Procedures.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>8.4</h4>
                The arbitration hearings will take place in Lisbon, Portugal.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>8.5</h4>
                YOU AND BetProtocol AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. Further, unless both you and BetProtocol agree otherwise, the arbitrator may not consolidate more than one person's claims with your claims, and may not otherwise preside over any form of a representative or class proceeding.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>8.6</h4>
                Notwithstanding any other provision in this Section 8 to the contrary, either party will at all times be entitled to seek and obtain injunctive relief from infringement or threatened infringement of its intellectual property rights, or misappropriation of its trade secrets, in any court having jurisdiction. Each party agrees that notice of arbitration may be serviced by written notice as provided by Section 11.1.
                
                <h3 style={{marginTop: 20, marginBottom: 10}}>9. Choice of Law and Alternate Forum</h3>
                
                These Terms shall be governed by, subject to, and interpreted in accordance with the laws of Portugal, without regard to conflict of laws principles. The parties agree that these Terms and the transactions contemplated therein shall not be governed by the United Nations Convention on Contracts for the International Sale of Goods. If arbitration cannot be compelled under Section 8, then the parties (a) hereby irrevocably consent to the jurisdiction of, and venue in, any federal or state court of competent jurisdiction located in Lisbon, Portugal for the purposes of adjudicating any action or proceeding to enforce these Terms, and (b) each party waives, to the fullest extent permitted by law, any objection that it may now or later have to such venue and any claim that any such action or proceeding brought in any such court has been brought in an inconvenient forum.
                
                <h3 style={{marginTop: 20, marginBottom: 10}}>10. Claims of Infringement</h3>
                
                If you believe that your Content has been copied in a way that constitutes copyright infringement, or your intellectual property rights have been otherwise violated, please notify BetProtocol’s Copyright Agent by written communication (by email with an attached and signed PDF or by fax) that sets forth the items specified below:
                fully describe such item, and provide the exact location of the material, such as the permanent URL for the web page containing the material.
                your full name, email address, telephone number, and full physical address.
                proof of copyright in the Content concerned, namely proof of registration under the DMCA; or, absent such registration, a detailed description of where the work was created, by whom, who or what the subject of the image is, and evidence to support your claim that you own the copyright.
                Include the following statement: “I swear, under penalty of perjury, that the information in the notification is accurate and that I am the copyright owner or am authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.”
                Sign, scan and email the document to support@BetProtocol.com. Please make sure that your spam filter does not block our response.
                
                <h3 style={{marginTop: 20}}>11. Other Terms</h3>
                
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>11.1 Notices.</h4>
                Except as otherwise specified in these Terms, all notices hereunder shall be in writing and shall be effectively given upon: (i) personal delivery, (ii) delivery of certified or registered mail, or by courier service, (iii) the first business day after sending by email. Notices shall be deemed to have been given, delivered and received upon receipt or attempted delivery (if receipt is refused), as the case may be, and the date of delivery identified by the applicable postal service on any return receipt card or confirmation by courier service, even if such delivery was refused. Notices to you will be addressed using the contact information you provided to us in connection with your account. Notices to us will be addressed to us at our contact information below. Either party may update their contact information for notice purposes by giving the other party appropriate notice under this Section 11.1
                Our address for notices: BetProtocol, Inc. Attention: Legal Notices : Av. Dom João II 404, Andar 4 Sala 46, Braga, Portugal 4715 - 275
                Email : Support@betprotocol.com
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>11.2 Entire Agreement</h4>
                These Terms, including the Privacy Policy and other terms, policies and guidelines incorporated by reference, constitute the entire agreement between you and BetProtocol and govern your use of the Service, superseding any prior agreements between you and BetProtocol with respect to the Service. The following Sections will survive any termination of these Terms: 1.2, 1.4, 1.5, 1.7, 1.8, 1.9, 1.10, 2.1, 2.2, 2.4, 2.7, and 3-11. Termination of these Terms shall not be construed to waive or release any claim that a party was entitled to assert at the time of such termination.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>11.3 Statute of Limitations</h4>
                Regardless of any statute or law to the contrary, any claim or cause of action arising out of a breach of these Terms or your use of the Service must be filed within one (1) year after such claim or cause of action arose or be forever barred. This limitation will not apply to misappropriation or infringement of intellectual property rights.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>11.4. Independent Contractors.</h4>
                No third-party beneficiaries; Assignment. BetProtocol and you are not legal partners or agents of each other; instead, our relationship is that of independent contractors. This contract is solely for your and our benefit. It is not for the benefit of any other person, except for permitted successors. You may not assign or delegate these Terms, your obligations, rights or responsibilities. Any attempt by you to do so is void. BetProtocol may assign or delegate these Terms, its obligations, rights and responsibilities, in whole or in part, at any time with or without notice to you.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>11.5 Government Use.</h4>
                If you are a U.S. government entity, you acknowledge that any software and documentation that are provided are “Commercial Items” as defined at 48 C.F.R. 2.101, and are being provided as commercial computer software subject to the restricted rights described in 48 C.F.R. 2.101 and 12.212.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>11.6 Savings Clause.</h4>
                If any provision of these Terms is found by a court of competent jurisdiction or arbitrator to be invalid or unenforceable, the parties agree that the court or arbitrator should endeavor to give effect to the parties' intentions as reflected in the provision, and the other provisions of these Terms remain in full force and effect. If the court or arbitrator cannot do so, then the parties agree that the court or arbitrator should strike the invalid or unenforceable provisions, and that the remaining provisions be given their full force and effect.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>11.7 Company Use.</h4>
                If you are using the Service on behalf of an organization, you are agreeing to these Terms for that organization and promising to BetProtocol that you have the authority to bind that organization to these Terms (in which event, “you” and “your” will refer to that organization). Nevertheless, each individual that uses the Service or accepts these Terms on behalf of an organization agrees that the permissions given to BetProtocol under these Terms, and the restrictions and limitations to the rights of persons and entities using the Service, apply to each such individual. You may use the Service only in compliance with these Terms and only if you have the power to form a contract with BetProtocol and are not barred under any applicable laws from doing so.
                
                <h4 style={{marginTop: 20, marginBottom: 10}}>11.8 Interpretation.</h4>
                The word “or” as used in these Terms has the meaning equivalent to “and/or”. The terms ‘include’ and ‘including’ will be deemed to be immediately followed by the phrase “without limitation”. These Terms do not confer any rights or benefits to any third party beneficiaries. The headings appearing at the beginning of sections have been inserted for identification and reference purposes only and must not be used to construe or interpret these Terms. The word “will” expresses an obligation equivalent to “shall”. These Terms will not be construed in favor of or against any party by reason of the extent to which any party participated in the preparation of these Terms. We each agree to contract in the English language. No failure or delay by either party in exercising any right under these Terms will constitute a waiver of that right.

            </div>

        );
    }
}

export default TermsConditions;

